# Generated by Django 3.1.5 on 2022-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='get_new_task_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pig',
            name='weight_count',
            field=models.IntegerField(default=0),
        ),
    ]
