# Generated by Django 3.1.5 on 2022-05-08 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.CharField(default=uuid.UUID('8f2c4ecf-eba9-40b3-bdd8-ba70def8d332'), max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('end_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('Future', 'Future'), ('Urgent', 'Urgent'), ('Later', 'Later')], max_length=256)),
                ('high_priority', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
